# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20170404_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='nama',
            new_name='name',
        ),
    ]
