# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20170404_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
