# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20170406_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id_level',
            field=models.IntegerField(choices=[(0, 'Parent Level'), (1, 'Child Level')], default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='id_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Category'),
        ),
    ]
