# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_be_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='be_read',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
