# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20170407_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id_parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='posts.Category'),
        ),
    ]
